name: Upload Impacted Targets
run-name: Upload Impacted Targets for ${{ github.ref_name }}
on: pull_request

permissions:
  contents: read

jobs:
  compute_impacted_targets:
    name: Compute Impacted Targets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Compute Impacted Targets
        uses: trunk-io/merge-action@1d96b7ab2f165191aa35d4e261a7794963847dd6
        with:
          trunk-token: ${{ secrets.TRUNK_ORG_TOKEN }}
          bazel-workspace-path: workspace
          verbose: 1
        env:
          API_URL: https://api.trunk-staging.io:443/v1/setImpactedTargets
